CREATE DATABASE IF NOT EXISTS SPOTON_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS SPOTON_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS SPOTON_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS SPOTON_ANALYTICS.CURATED;