-- =====================================================
-- DAILY RAW INGESTION TASK
-- Simulates new operational incident data daily
-- Runs at 11:55 PM America/Chicago
-- =====================================================

CREATE OR REPLACE TASK SPOTON_ANALYTICS.STAGING.DAILY_RAW_INGESTION
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 55 23 * * * America/Chicago'
AS
INSERT INTO SPOTON_ANALYTICS.RAW.RAW_INCIDENTS_TABLE
SELECT
    UUID_STRING() AS INCIDENT_ID,
    CASE 
        WHEN UNIFORM(1,4,RANDOM()) = 1 THEN 'NORTHEAST'
        WHEN UNIFORM(1,4,RANDOM()) = 2 THEN 'MIDWEST'
        WHEN UNIFORM(1,4,RANDOM()) = 3 THEN 'SOUTH'
        ELSE 'WEST'
    END AS REGION,
    'Storm' AS INCIDENT_TYPE,
    CURRENT_TIMESTAMP() AS START_TIME,
    CURRENT_TIMESTAMP() + INTERVAL '3 HOURS' AS END_TIME,
    'Closed' AS STATUS,
    UNIFORM(10,200,RANDOM()) AS AFFECTED_STORES,
    UNIFORM(10000,500000,RANDOM()) AS ESTIMATED_LOSS,
    UNIFORM(12,48,RANDOM()) AS SLA_HOURS,
    'Medium' AS SEVERITY,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 150));

-- Resume task
ALTER TASK SPOTON_ANALYTICS.STAGING.DAILY_RAW_INGESTION RESUME;



-- =====================================================
-- DAILY INCREMENTAL LOAD TASK
-- Processes only new rows based on LOAD_TIMESTAMP
-- Runs at 12:00 AM America/Chicago
-- =====================================================

CREATE OR REPLACE TASK SPOTON_ANALYTICS.STAGING.DAILY_INCREMENTAL_LOAD
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 0 * * * America/Chicago'
AS
INSERT INTO SPOTON_ANALYTICS.STAGING.CLEANED_INCIDENTS
(
    INCIDENT_ID,
    REGION,
    INCIDENT_TYPE,
    START_TIME,
    END_TIME,
    INCIDENT_DURATION_HOURS,
    STATUS,
    AFFECTED_STORES,
    ESTIMATED_LOSS,
    SLA_HOURS,
    SEVERITY,
    SLA_BREACHED,
    LOAD_TIMESTAMP
)
SELECT
    INCIDENT_ID,
    REGION,
    INCIDENT_TYPE,
    START_TIME,
    END_TIME,
    DATEDIFF(HOUR, START_TIME, END_TIME) AS INCIDENT_DURATION_HOURS,
    STATUS,
    AFFECTED_STORES,
    ESTIMATED_LOSS,
    SLA_HOURS,
    SEVERITY,
    CASE 
        WHEN DATEDIFF(HOUR, START_TIME, END_TIME) > SLA_HOURS THEN 1
        ELSE 0
    END AS SLA_BREACHED,
    LOAD_TIMESTAMP
FROM SPOTON_ANALYTICS.RAW.RAW_INCIDENTS_TABLE r
WHERE r.LOAD_TIMESTAMP >
(
    SELECT COALESCE(MAX(LOAD_TIMESTAMP), '1900-01-01')
    FROM SPOTON_ANALYTICS.STAGING.CLEANED_INCIDENTS
);

-- Resume task
ALTER TASK SPOTON_ANALYTICS.STAGING.DAILY_INCREMENTAL_LOAD RESUME;